# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Glib-Event
version:      0.1
version_from: Event.pm
installdirs:  site
requires:
    Event:                         1
    ExtUtils::PkgConfig:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
